wxSVG: fix build failure against `gcc-13`
Without the change `wxSVG` fails the build in `master` as
https://hydra.nixos.org/build/248172755:

    libwx_gtk3u_xrc-3.2.so: undefined reference to `std::ios_base_library_init()@GLIBCXX_3.4.32'
    collect2: error: ld returned 1 exit status
    make[1]: *** [Makefile:416: svgview] Error 1

This happens due to mix of `gcc-12` / `gcc-13` `libstdc++` libraries.

THe fix just applies upstream fix for `wxSVG` for `gcc-13`.